#
# This file and its contents are supplied under the terms of the
# Common Development and Distribution License ("CDDL"), version 1.0.
# You may only use this file in accordance with the terms of version
# 1.0 of the CDDL.
#
# A full copy of the text of the CDDL should have accompanied this
# source.  A copy of the CDDL is also available via the Internet at
# http://www.illumos.org/license/CDDL.
#

#
# Copyright 2017 Nexenta Systems, Inc.
#

[DEFAULT]
pre = setup
quiet = False
pre_user = root
user = root
timeout = 2400
post_user = root
post = cleanup
outputdir = /var/tmp/test_results

[/opt/zfs-tests/tests/stress/mirror_002]
tests = ['mirror_002']

[/opt/zfs-tests/tests/stress/mirror_003]
tests = ['mirror_003']

[/opt/zfs-tests/tests/stress/mirror_004]
tests = ['mirror_004']

[/opt/zfs-tests/tests/stress/mirror_005]
tests = ['mirror_005']

[/opt/zfs-tests/tests/stress/mirror_006]
tests = ['mirror_006']

[/opt/zfs-tests/tests/stress/raidz_001]
tests = ['raidz_001']

[/opt/zfs-tests/tests/stress/raidz_002]
tests = ['raidz_002']

[/opt/zfs-tests/tests/stress/slog_001]
tests = ['slog_001']

[/opt/zfs-tests/tests/stress/slog_002]
tests = ['slog_002']
